spring:
  application:
    name: ms-mq-stream
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        example-topic-input:
          destination: test-topic
        example-topic-output:
          destination: test-topic

server:
  port: 18510